id: Microsoft Graph - Test
version: -1
name: Microsoft Graph - Test
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 6b8a8037-becc-4509-840d-bb2a40d1b2be
    type: start
    task:
      id: 6b8a8037-becc-4509-840d-bb2a40d1b2be
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "10"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "1":
    id: "1"
    taskid: 7be5210d-e345-464c-8f18-8f5e89ad6a4a
    type: regular
    task:
      id: 7be5210d-e345-464c-8f18-8f5e89ad6a4a
      version: -1
      name: Create test user
      description: Creates a new user.
      script: '|||msgraph-user-create'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      account_enabled: {}
      display_name:
        simple: Graph Test - DELETE
      mail_nickname:
        simple: graph
      on_premises_immutable_id: {}
      other_properties:
        simple: jobTitle=Test,city=Tel Aviv
      password:
        simple: Aa-123456789Bc!
      user_principal_name:
        simple: ${GeneratedUUID}@${inputs.baseurl}
    continueonerror: true
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "2":
    id: "2"
    taskid: b86a5821-8d91-490a-82f2-2ce288167ef4
    type: regular
    task:
      id: b86a5821-8d91-490a-82f2-2ce288167ef4
      version: -1
      name: Get User
      description: Retrieve the properties and relationships of user object. [link](https://docs.microsoft.com/en-us/graph/api/user-update?view=graph-rest-1.0)
      script: '|||msgraph-user-get'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      properties: {}
      user:
        simple: ${MSGraphUser.UserPrincipalName}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 720
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "3":
    id: "3"
    taskid: 91a9f7a3-c503-4c2a-8604-eb7f2adf62ad
    type: regular
    task:
      id: 91a9f7a3-c503-4c2a-8604-eb7f2adf62ad
      version: -1
      name: Update user phone number
      description: Update the properties of a user object.
      script: '|||msgraph-user-update'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "8"
    scriptarguments:
      updated_fields:
        simple: mobilePhone=050505050
      user:
        simple: ${MSGraphUser.UserPrincipalName}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 895
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "4":
    id: "4"
    taskid: 83eed85c-0d05-4ab5-89ba-317b8f2ed6b7
    type: regular
    task:
      id: 83eed85c-0d05-4ab5-89ba-317b8f2ed6b7
      version: -1
      name: Get Delta (mobilePhone)
      description: Get newly created, updated, or deleted users without having to
        perform a full read of the entire user collection.
      script: '|||msgraph-user-get-delta'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "5"
    scriptarguments:
      execution-timeout:
        simple: "30"
      properties:
        simple: mobilePhone
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1245
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "5":
    id: "5"
    taskid: cf983217-06c2-4138-8b6e-6f5bcb540f1d
    type: regular
    task:
      id: cf983217-06c2-4138-8b6e-6f5bcb540f1d
      version: -1
      name: Block user
      description: Terminate users session from all Office 365 and prevents it from
        siginin in
      script: '|||msgraph-user-terminate-session'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "6"
    scriptarguments:
      user:
        simple: oren@${inputs.baseurl}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1420
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "6":
    id: "6"
    taskid: 234b6a98-bca4-4f4e-8b91-af0ae1e1ff40
    type: regular
    task:
      id: 234b6a98-bca4-4f4e-8b91-af0ae1e1ff40
      version: -1
      name: Sleep for 30 seconds
      description: Sleep for X seconds
      scriptName: Sleep
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "7"
    scriptarguments:
      seconds:
        simple: "30"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1595
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "7":
    id: "7"
    taskid: 94601336-35c2-4a56-8ab2-7de5b3f9c131
    type: regular
    task:
      id: 94601336-35c2-4a56-8ab2-7de5b3f9c131
      version: -1
      name: Unblock User
      description: Unblock a user.
      script: '|||msgraph-user-unblock'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "15"
    scriptarguments:
      user:
        simple: oren@${inputs.baseurl}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1770
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "8":
    id: "8"
    taskid: a9ba033d-e0b0-46a1-8316-9ca622dd4f08
    type: regular
    task:
      id: a9ba033d-e0b0-46a1-8316-9ca622dd4f08
      version: -1
      name: Delete user
      description: Deletes an exsiting user.
      script: '|||msgraph-user-delete'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      user:
        simple: ${GeneratedUUID}@${inputs.baseurl}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1070
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "9":
    id: "9"
    taskid: d667ff5c-cb1f-4364-8912-4dc908c4f373
    type: title
    task:
      id: d667ff5c-cb1f-4364-8912-4dc908c4f373
      version: -1
      name: Done!
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 3695
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "10":
    id: "10"
    taskid: 600f4428-f55f-49d6-820b-139786c41b6b
    type: regular
    task:
      id: 600f4428-f55f-49d6-820b-139786c41b6b
      version: -1
      name: Delete Context
      description: Delete field from context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "18"
    scriptarguments:
      all:
        simple: "yes"
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "14":
    id: "14"
    taskid: 2e4cbf35-4238-4f66-8d68-ba362e5feb7b
    type: regular
    task:
      id: 2e4cbf35-4238-4f66-8d68-ba362e5feb7b
      version: -1
      name: List Users
      description: Retrieve a list of user objects.
      script: '|||msgraph-user-list'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "9"
    scriptarguments:
      next_page: {}
      properties:
        simple: id,userPrincipalName
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 3520
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "15":
    id: "15"
    taskid: fa41f4bd-aed2-45a1-8cdf-6d9dd5a8af9c
    type: regular
    task:
      id: fa41f4bd-aed2-45a1-8cdf-6d9dd5a8af9c
      version: -1
      name: Create test user with no "Other_properties"
      description: Creates a new user.
      script: '|||msgraph-user-create'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "16"
    scriptarguments:
      account_enabled: {}
      display_name:
        simple: Test User
      mail_nickname:
        simple: Test
      on_premises_immutable_id: {}
      other_properties: {}
      password:
        simple: password123123!
      user_principal_name:
        simple: ${GeneratedUUID}test@${inputs.baseurl}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1945
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "16":
    id: "16"
    taskid: d1caf36f-6883-44a4-8d1e-4d9213f15a8e
    type: regular
    task:
      id: d1caf36f-6883-44a4-8d1e-4d9213f15a8e
      version: -1
      name: Get User
      description: 'Retrieves the properties and relationships of user object. for
        more information, visit: https://docs.microsoft.com/en-us/graph/api/user-update?view=graph-rest-1.0)'
      script: '|||msgraph-user-get'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "19"
    scriptarguments:
      properties: {}
      user:
        simple: ${GeneratedUUID}test@${inputs.baseurl}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2120
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "17":
    id: "17"
    taskid: 0081e283-2784-4414-8f44-0acb50f1af91
    type: regular
    task:
      id: 0081e283-2784-4414-8f44-0acb50f1af91
      version: -1
      name: Delete User
      description: Deletes an exsiting user.
      script: '|||msgraph-user-delete'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "24"
    scriptarguments:
      user:
        simple: ${GeneratedUUID}test@${inputs.baseurl}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 3170
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "18":
    id: "18"
    taskid: cf9d136a-d604-4cc0-881b-01e7708656ec
    type: regular
    task:
      id: cf9d136a-d604-4cc0-881b-01e7708656ec
      version: -1
      name: Generate UUID for user principal name
      description: Generates random UUID
      scriptName: GenerateUUID
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "19":
    id: "19"
    taskid: 1e8e2b67-94df-405a-810b-cae3f80f4bda
    type: regular
    task:
      id: 1e8e2b67-94df-405a-810b-cae3f80f4bda
      version: -1
      name: Create test user (manager)
      description: Creates a new user.
      script: '|||msgraph-user-create'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "20"
    scriptarguments:
      account_enabled: {}
      display_name:
        simple: Graph Test - DELETE
      mail_nickname:
        simple: graph
      on_premises_immutable_id: {}
      other_properties:
        simple: jobTitle=Test,city=Tel Aviv
      password:
        simple: Aa-123456789Bc!
      user_principal_name:
        simple: ${GeneratedUUID}manager@${inputs.baseurl}
    continueonerror: true
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2295
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "20":
    id: "20"
    taskid: cb1d8651-6efc-4e92-84af-4bc2fc8893f2
    type: regular
    task:
      id: cb1d8651-6efc-4e92-84af-4bc2fc8893f2
      version: -1
      name: Get User (manager)
      description: Retrieve the properties and relationships of user object. [link](https://docs.microsoft.com/en-us/graph/api/user-update?view=graph-rest-1.0)
      script: '|||msgraph-user-get'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "21"
    scriptarguments:
      properties: {}
      user:
        simple: ${GeneratedUUID}manager@${inputs.baseurl}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2470
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "21":
    id: "21"
    taskid: a359e85c-2745-49ac-8478-6bf56dfc4a53
    type: regular
    task:
      id: a359e85c-2745-49ac-8478-6bf56dfc4a53
      version: -1
      name: Assign test user manager
      description: 'Assigns a manager to the user. Permissions: - User.ReadWrite.All
        (Delegated & Application)'
      script: '|||msgraph-user-assign-manager'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "22"
    scriptarguments:
      manager:
        simple: ${GeneratedUUID}manager@${inputs.baseurl}
      user:
        simple: ${GeneratedUUID}test@${inputs.baseurl}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2645
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "22":
    id: "22"
    taskid: 92429cd6-14f4-426d-89da-144566618b92
    type: regular
    task:
      id: 92429cd6-14f4-426d-89da-144566618b92
      version: -1
      name: Get test user manager
      description: Retrieves the properties from the manager of a user
      script: '|||msgraph-user-get-manager'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "23"
    scriptarguments:
      user:
        simple: ${GeneratedUUID}test@${inputs.baseurl}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2820
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "23":
    id: "23"
    taskid: abd7a7af-c90a-4cdd-8609-242d23eb28d9
    type: regular
    task:
      id: abd7a7af-c90a-4cdd-8609-242d23eb28d9
      version: -1
      name: Get manager direct reports
      description: Retrieves the direct reports for a user. Direct reports are the
        people who have that user configured as their manager.
      script: '|||msgraph-direct-reports'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "17"
    scriptarguments:
      user:
        simple: ${GeneratedUUID}manager@${inputs.baseurl}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2995
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "24":
    id: "24"
    taskid: 0a9fdf6a-40f3-4873-8d60-4bbcdbc302bb
    type: regular
    task:
      id: 0a9fdf6a-40f3-4873-8d60-4bbcdbc302bb
      version: -1
      name: Delete User (manager)
      description: Deletes an exsiting user.
      script: '|||msgraph-user-delete'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "14"
    scriptarguments:
      user:
        simple: ${GeneratedUUID}manager@${inputs.baseurl}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 3345
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 3710,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
inputs:
- key: baseurl
  value:
    simple: demistodev.onmicrosoft.com
  required: true
  description: ""
  playbookInputQuery: null
outputs: []